### ISSUE TITLE
Re adding the !profile commands 

### ISSUE THREAD

**Issue by Blackoutburst** [Blackoutburst/Wally#15]
The profile commands used to show player Hypixel level and AP but the plancke.io generator was really unstable and was not working on some linux device for some reason. So for this reason the commands got disabled

The goal is to bring back this commands without using the plancke.io generator and maybe add more Player information such as karma.

The command should follow the standard like !stats and !compare, meaning a canvas 600x400 suporting user custom background/title and so on

**Comment by Blackoutburst** [comment]
Looks at `src/commands/CommandStats.java` since the bases are similar

**Comment by eatmyvenom** [comment]
I have something similar [here](http://eatmyvenom.me/share/partygames/player.html) if you want to check it out

**Comment by eatmyvenom** [comment]
Technically you can piggyback off of my site by simply linking it and I can add embeds, however this requires them to also be in my database which could get really expensive for me really fast.

**Comment by eatmyvenom** [comment]
I have done a bit of experimenting with this section of code now. The whole system works flawlessly on my linux machine, I have jdk8 enabled at the moment so I don't see how it could be a version issue either. I have had some minor java issues on a raspi however so that could be it. I do firmly believe this can be improved but kept in mostly the same state.

**Comment by Blackoutburst** [comment]
Actually yes something like you have can be good but you actually use the planck.io generator for the level and AP but for some reason since Wally run on Arch Linux plancke generator cessead to work that why i disabled the command

**Comment by Blackoutburst** [comment]
`!profile` got replaced by `!whois` so the issues is fixed
