### ISSUE TITLE
User not inside leaderboard display rank 10 000 on every stats

### ISSUE THREAD

**Issue by Blackoutburst** [Blackoutburst/Wally#25]
**Describe the bug**
When using `!stats` on a player not inside the leaderboard it display rank 10 000 for all their stats

**To Reproduce**
1. use `!stats` on someone not inside the leaderboard

**Expected behavior**
This should not display ranks after the stats like it used to be

**Screenshots**
![stats](https://user-images.githubusercontent.com/30992311/112703320-cd90f580-8e96-11eb-8c00-8ebca798cfc0.png)

**Comment by eatmyvenom** [comment]
This was caused by the `GeneralUtils` refractor. I'm adding a fix for this now.
