### ISSUE TITLE
Search commands does not support player title and custom background

### ISSUE THREAD

**Issue by Blackoutburst** [Blackoutburst/Wally#26]
**Describe the bug**
When displaying player stats using `!search` their title and background does not display

**To Reproduce**
1. use `!search` on any player with a custom title and/or background

**Expected behavior**
It should display everything like we used `!stats` on the player

**Screenshots**
Output
![stats](https://user-images.githubusercontent.com/30992311/112703474-5a3bb380-8e97-11eb-865d-4daac855afe6.png)
Expected
![stats](https://user-images.githubusercontent.com/30992311/112703477-6293ee80-8e97-11eb-8f1b-30382b9c0fb1.png)

**Comment by eatmyvenom** [comment]
Issue in the code is the `getCustomBackground` needing uuid but getting name.
